version: '3.8'

services:
  # 前端服務
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    networks:
      - interview-network

  # 後端服務
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/interview_platform
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=interview_platform_users
      - JWT_SECRET=local_development_secret_key
      - JWT_EXPIRES_IN=7d
    networks:
      - interview-network

  # MongoDB 數據庫 (用於非結構化數據)
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - interview-network

  # PostgreSQL 數據庫 (用於用戶和權限管理)
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=interview_platform_users
    networks:
      - interview-network

  # Adminer 數據庫管理工具 (可選)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - interview-network

networks:
  interview-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data: 